/**
 * The Pegasus topology — the qubit connectivity of D-Wave's Advantage QPUs.
 *
 * A straight port of `dwave_networkx.pegasus_graph(m)` and `pegasus_layout`
 * with their defaults (`fabric_only=True`, `offsets_index=0`, integer labels,
 * `crosses=False`). Labels are the same linear indices `dwave_networkx` uses,
 * so a chain printed here names the same qubits as one printed by Ocean.
 *
 * This is the IDEAL graph: every qubit and coupler the design calls for. A real
 * QPU's working graph is a subgraph of it, missing whatever failed fabrication,
 * and differs machine to machine; reading it needs a Leap account.
 *
 * Correctness is not argued here but checked: `npm run verify:embed` compares
 * the node set, edge set and layout against fixtures generated by
 * `dwave_networkx` itself (`scripts/gen-pegasus-fixture.py`).
 *
 * Coordinates are `(u, w, k, z)`: orientation (0 vertical, 1 horizontal),
 * perpendicular tile offset, perpendicular offset within the tile (0–11), and
 * parallel tile offset. `pegasusGraph(16)` is the full Advantage lattice,
 * 5,640 qubits.
 */

export type PegasusCoord = readonly [u: number, w: number, k: number, z: number];

/** An undirected hardware graph; labels are `dwave_networkx` linear indices. */
export type HardwareGraph = {
  family: 'pegasus';
  m: number;
  /** Qubit labels, ascending. */
  nodes: number[];
  /** Couplers as `[a, b]` with `a < b`, ascending. */
  edges: [number, number][];
};

const TILE = 12;

/** `offsets_index=0` in `dwave_networkx`: [vertical, horizontal]. */
const OFFSETS: readonly [readonly number[], readonly number[]] = [
  [2, 2, 2, 2, 10, 10, 10, 10, 6, 6, 6, 6],
  [6, 6, 6, 6, 2, 2, 2, 2, 10, 10, 10, 10],
];

export function pegasusToLinear(m: number, [u, w, k, z]: PegasusCoord): number {
  return ((m * u + w) * TILE + k) * (m - 1) + z;
}

export function linearToPegasus(m: number, r: number): PegasusCoord {
  const m1 = m - 1;
  const z = r % m1;
  r = (r - z) / m1;
  const k = r % TILE;
  r = (r - k) / TILE;
  const w = r % m;
  const u = (r - w) / m;
  return [u, w, k, z];
}

export function pegasusGraph(m: number): HardwareGraph {
  if (!Number.isInteger(m) || m < 2) throw new Error(`pegasusGraph: m must be an integer ≥ 2, got ${m}`);
  const m1 = m - 1;
  const [off0, off1] = OFFSETS;
  const label = (q: PegasusCoord) => pegasusToLinear(m, q);

  // `fabric_only=True`: drop the dangling qubits at the lattice boundary.
  // Index 0 of each pair is read from the HORIZONTAL offsets, as upstream does.
  const fabricStart = [Math.min(...off1), Math.min(...off0)];
  const fabricEnd = [TILE - Math.max(...off1), TILE - Math.max(...off0)];
  const kFrom = (u: number, w: number) => (w === 0 ? fabricStart[u] : 0);
  const kTo = (u: number, w: number) => TILE - (w === m1 ? fabricEnd[u] : 0);
  const qfilter = ([u, w, k]: PegasusCoord) => {
    if (w === 0) return k >= fabricStart[u];
    if (w === m1) return k < TILE - fabricEnd[u];
    return true;
  };

  const seen = new Set<string>();
  const edges: [number, number][] = [];
  const add = (p: PegasusCoord, q: PegasusCoord) => {
    let a = label(p);
    let b = label(q);
    if (a > b) [a, b] = [b, a];
    const key = `${a},${b}`;
    if (seen.has(key)) return;
    seen.add(key);
    edges.push([a, b]);
  };

  // External couplers: a qubit to its neighbour along the same line.
  for (let u = 0; u < 2; u++)
    for (let w = 0; w < m; w++)
      for (let k = kFrom(u, w); k < kTo(u, w); k++)
        for (let z = 0; z < m1 - 1; z++) add([u, w, k, z], [u, w, k, z + 1]);

  // Odd couplers: the pair (2j, 2j+1) running side by side.
  for (let u = 0; u < 2; u++)
    for (let w = 0; w < m; w++)
      for (let k = kFrom(u, w); k < kTo(u, w); k += 2)
        for (let z = 0; z < m1; z++) add([u, w, k, z], [u, w, k + 1, z]);

  // Internal couplers: a vertical qubit to every horizontal qubit it crosses.
  for (let w = 0; w < m; w++)
    for (let kk = 0; kk < TILE; kk++)
      for (let k = w ? 0 : off1[kk]; k < (w < m1 ? TILE : off1[kk]); k++)
        for (let z = 0; z < m1; z++) {
          const p: PegasusCoord = [0, w, k, z];
          const q: PegasusCoord = [1, z + (kk < off0[k] ? 1 : 0), kk, w - (k < off1[kk] ? 1 : 0)];
          if (qfilter(p) && qfilter(q)) add(p, q);
        }

  edges.sort((x, y) => x[0] - y[0] || x[1] - y[1]);
  const nodes = [...new Set(edges.flat())].sort((a, b) => a - b);
  return { family: 'pegasus', m, nodes, edges };
}

/**
 * Node positions as `dwave_networkx.pegasus_layout(G)` returns them: x in
 * [0, 1] left to right, y in [−1, 0] top to bottom (the y axis is inverted, as
 * in every Pegasus picture D-Wave publishes). A renderer drawing in screen
 * coordinates uses `(x, −y)`.
 */
export function pegasusLayout(graph: HardwareGraph): Map<number, [number, number]> {
  const { m } = graph;
  const [vOff, hOff] = OFFSETS;
  const tileCenter = TILE / 2 - 0.5;
  const scale = 1 / (m * TILE);

  const raw = graph.nodes.map((v): [number, number] => {
    const [u, w, k, z] = linearToPegasus(m, v);
    const p = k % 2 ? -0.1 : 0.1;
    return u
      ? [(z * TILE + hOff[k] + tileCenter) * scale, (-TILE * w - k - p) * scale]
      : [(TILE * w + k + p) * scale, (-z * TILE - vOff[k] - tileCenter) * scale];
  });

  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const [x, y] of raw) {
    minX = Math.min(minX, x);
    maxX = Math.max(maxX, x);
    minY = Math.min(minY, y);
    maxY = Math.max(maxY, y);
  }
  const sx = maxX - minX;
  const sy = maxY - minY;

  const pos = new Map<number, [number, number]>();
  graph.nodes.forEach((v, i) => {
    const [x, y] = raw[i];
    pos.set(v, [(x - minX) * (1 / sx), (y - maxY) * (1 / sy)]);
  });
  return pos;
}

/** Neighbour lists keyed by qubit label. */
export function adjacency(graph: HardwareGraph): Map<number, number[]> {
  const adj = new Map<number, number[]>(graph.nodes.map((v) => [v, []]));
  for (const [a, b] of graph.edges) {
    adj.get(a)!.push(b);
    adj.get(b)!.push(a);
  }
  return adj;
}
